### ISSUE TITLE
gltf 2.0 models rendering black in babylon.js and cesium viewers when normals are not specified

### ISSUE THREAD

**Issue by kcoley** [AnalyticalGraphicsInc/gltf-vscode#28] opened 2017-08-11 22:11 UTC
Hello!
I have been generating a few glTF 2.0 models and testing them with the glTF Tools in Visual Studio Code.  However, I have found that when generating models without normals specified, the babylon.js and cesium viewers in VS Code renders them as black, whereas specifying the normals allows them to render as expected.  It seems that these viewers are not calculating the flat normals when they are not provided within the gltf file.  

I created a gist example, where I provide two gltf 2.0 files (and their binary data) for a triangle with normals and without normals (https://gist.github.com/kcoley/acb49a8bcea638c78e77327b7dbc76e8).

For reference, the babylonjs sandbox url is able to render the material on the glTF triangle file without normals specified.

I tested this using Windows 10.  Hopefully this should provide enough info, but please let me know if you have any questions on this issue.

Thanks!
~Kacey

**Comment by emackey** [comment] 2017-08-12 17:09
@bghgary @pjcozzi Are viewers expected to calculate missing normals?  Does the spec explicitly state that normals are the responsibility of the exporter?

@kcoley Part of the "spirit of glTF" is that we try to move all processing burdens to the exporters and glTF creators, and keep those burdens off the viewers and runtime engines.  The model is intended to be in a ready-to-render state when it arrives, to the extent reasonable, because the runtime may be on a battery-operated mobile device without a lot of spare cycles for calculating normals that could have been supplied.  So my suggestion would be, always supply the normals, but I've asked some other members of the working group if there's a more official statement on this.

**Comment by bghgary** [comment] 2017-08-12 18:09
@emackey Per implementation note, https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes

> Implementation note: When normals are not specified, client implementations should calculate flat normals.

**Comment by emackey** [comment] 2017-09-19 15:35
@kcoley Thanks for writing this up.  I lost track of this a bit, but the Cesium engine now has an issue open to fix it here:  AnalyticalGraphicsInc/cesium#5838.  I don't know if the BabylonJS folks have a corresponding issue.

**Comment by emackey** [comment] 2017-09-19 17:31
Ah, I may just need a Babylon refresh, once the issue is resolved.

> How often do you update the BabylonJS bits?

Not on any schedule, which is a problem for all the engines I guess.  I've avoided adding CDN links because I need this plugin to work on a disconnected network with no CDN access.  I suppose there should be a recurring task to update each of the engines at some frequency.  I wonder if I could convince a bot to file those PRs for me, hmmm.

> though it is currently broken right now

Do you have an issue handy for this, that we could link to from here?  Thanks @bghgary!

**Comment by bghgary** [comment] 2017-09-19 19:47
No, unfortunately, we don't have an issue on GitHub for this. Do we need one?

**Comment by emackey** [comment] 2017-09-19 19:52
No not for my sake, thanks.

**Comment by bghgary** [comment] 2017-09-20 00:14
Normals issue is now fixed.

**Comment by najadojo** [comment] 2017-10-27 21:44
This issue looks resolved in the current version of the extension.

**Comment by emackey** [comment] 2017-10-27 22:38
The issue should be resolved for Babylon with the next published release of the extension (coming soon!).  Cesium has a separate issue to track this, AnalyticalGraphicsInc/cesium#5838.

I am going to close this since it's not a bug in this VSCode extension itself.  Thanks everyone!

**Closed by emackey** 2017-10-27 22:38 UTC
